### ISSUE TITLE
fork

### ISSUE THREAD

**Issue by noppelmax** [gre/genetic-server#1]
Hey gre,

i have build a enhanced version of this one at https://github.com/noppelmax/genetic-server. I started with your project but rewrote most parts as i need for example multiple clients support. I also set a database at the backend. I have wrote credits to you in my README.md. I hope this is fine for you. Is it? Would be nice to hear from your. 

Best Regards,
max

**Comment by gre** [comment]
sure, happy this helped you to build your stuff :)
